# Generated by Django 4.2 on 2023-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
